/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 750e1cb72512934b8c0cbae29f3af537)
interface __BaseEnv_Env {
	CHAT_ROOM: DurableObjectNamespace<import("./src/index").ChatRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChatRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
