/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d15c584202e4c8cc3c450e1ca8bdbc4d)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
