/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jobs.jsonc --include-runtime=false worker-configuration.jobs.d.ts` (hash: fc1511c5cd0c33ecbc1359446ce3668d)
interface __BaseEnv_Env {
	RESULTS: KVNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
