/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.api.jsonc --include-runtime=false worker-configuration.api.d.ts` (hash: de3a32b7404040f381201356b62989c6)
interface __BaseEnv_Env {
	TASKS: Queue;
	CATALOG: Fetcher /* module-catalog */;
	ACCOUNTS: Fetcher /* module-accounts */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/api");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
