/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jobs.jsonc --include-runtime=false worker-configuration.jobs.d.ts` (hash: 70f7cf9a5c1a6eb10251392463a311fd)
interface __BaseEnv_Env {
	RESULTS: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/jobs");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
