/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.catalog.jsonc --config=wrangler.accounts.jsonc --include-runtime=false worker-configuration.catalog.d.ts` (hash: 187a8a269a0a8f2c31ebb8ac8eed2c9b)
interface __BaseEnv_Env {
	IDENTITY: Service<typeof import("./src/accounts").Identity>;
	MEMBERSHIP: Service<typeof import("./src/accounts").Membership>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/catalog");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
