/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.api.jsonc --include-runtime=false worker-configuration.api.d.ts` (hash: f6ea165a687ba45b4c72750396242fe1)
interface __BaseEnv_Env {
	TASKS: Queue;
	CATALOG: Fetcher /* module-catalog */;
	ACCOUNTS: Fetcher /* module-accounts */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
