/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.api.jsonc --config=wrangler.catalog.jsonc --config=wrangler.accounts.jsonc --include-runtime=false worker-configuration.api.d.ts` (hash: a2b2d46f6c859dc5177097d14fe4ac14)
interface __BaseEnv_Env {
	TASKS: Queue;
	NATIVE_CATALOG: Service<typeof import("./src/catalog").Catalog>;
	UNTRUSTED_CATALOG: Service<typeof import("./src/catalog").Catalog>;
	CATALOG: Service<typeof import("./src/catalog").default>;
	ACCOUNTS: Service<typeof import("./src/accounts").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/api");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
