/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.catalog.jsonc --include-runtime=false worker-configuration.catalog.d.ts` (hash: 2118672e85a5a9b3dc89d6bbc3b77f24)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
