/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.catalog.jsonc --include-runtime=false worker-configuration.catalog.d.ts` (hash: 2b1ca850d98a7d70335cdddc0cd696e0)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/catalog");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
