/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.accounts.jsonc --include-runtime=false worker-configuration.accounts.d.ts` (hash: 8505bf674cf43a6766837b28dc175442)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/accounts");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
