import { cronDialectAmbiguity, parseCron, parseCronMetadata } from '@velajs/vela';
import { z } from 'zod';
import { selectDeploymentTarget, type DeploymentTarget } from './deploy-check.config.js';

export interface DeploymentIssue {
  readonly code: string;
  readonly message: string;
}

const rowsSchema = z.array(
  z.object({ kind: z.string().min(1), target: z.string().min(1), meta: z.unknown() }),
);
const metadataSchema = z.record(z.string(), z.unknown());

/** Accept existing `vela entrypoint list --json` output without loading an application. */
function entrypoints(value: unknown) {
  const parsed = rowsSchema.safeParse(value);
  if (!parsed.success)
    throw new Error('Entrypoint snapshot must be an array of { kind, target, meta } rows.');
  return parsed.data
    .filter((row) => !(row.target === '(no entrypoints)' && row.meta === ''))
    .map((row) => {
      let meta: unknown = row.meta;
      if (typeof meta === 'string') {
        try {
          meta = JSON.parse(meta);
        } catch {
          throw new Error('Invalid JSON metadata in entrypoint snapshot.');
        }
      }
      // Unknown kinds can contain arbitrary metadata; known ones validate below.
      return { kind: row.kind, meta };
    });
}

export interface DeploymentPlan {
  readonly status: 'passed' | 'failed';
  readonly target: DeploymentTarget;
  readonly errors: readonly DeploymentIssue[];
  readonly warnings: readonly DeploymentIssue[];
}

const queueName = z
  .string()
  .min(1)
  .refine((value) => value.trim() === value);
const registrationSchema = z.object({
  name: queueName,
  binding: queueName.optional(),
  consumers: z.array(queueName),
});
const moduleConsumerSchema = z.object({ consumers: z.array(queueName) });

/** Kinds older CLIs listed; their rows would silently stop counting. */
const removedKinds: Readonly<Record<string, string>> = {
  'cf:scheduled': 'Workers cron jobs are core @Cron handlers (schedule:cron)',
  'cf:vela-cron': 'Workers cron jobs are core @Cron handlers (schedule:cron)',
  'cf:queue:producer':
    'QueueModule.registerQueue({ name, binding }) publishes queue producers as queue:registration',
};

interface QueueRegistrationRow {
  readonly binding: string | undefined;
  readonly consumers: string[];
}

/** Compare literal dispatch keys; equivalent cron expressions are not interchangeable. */
export function checkDeployment(
  rawConfig: unknown,
  environment: string,
  snapshot: unknown,
): DeploymentPlan {
  const target = selectDeploymentTarget(rawConfig, environment);
  const errors: DeploymentIssue[] = [];
  const warnings: DeploymentIssue[] = [];
  const report = (code: string, message: string) => errors.push({ code, message });
  const validateCron = (cron: string): void => {
    if (!parseCron(cron, { dialect: 'cloudflare', timeZone: 'UTC' })) {
      report('invalid-cron', 'A trigger or handler has an invalid Cloudflare cron expression.');
    }
  };
  const crons = new Set(target.crons);
  if (crons.size !== target.crons.length)
    report('duplicate-cron', 'Duplicate cron trigger configuration.');
  for (const cron of crons) validateCron(cron);
  const handlerCrons = new Set<string>();
  // Physical queues raw @QueueConsumer handlers claim.
  const rawQueues = new Set<string>();
  // Logical queues @Processor providers handle, and QueueModule registrations.
  const processedQueues = new Set<string>();
  const registrations = new Map<string, QueueRegistrationRow>();
  // True when the queue driver consumes natively through QueueModule.
  let moduleConsumer = false;
  // Physical queues the native module consumer pins (its cf:queue:module rows).
  const modulePins = new Set<string>();
  const stale = (kind: string, replacement: string): void => {
    report(
      'stale-entrypoint-snapshot',
      `The snapshot lists the removed '${kind}' metadata, so it was generated by an older ` +
        `CLI. ${replacement}; regenerate the snapshot with \`vela entrypoint list --json\`.`,
    );
  };
  for (const row of entrypoints(snapshot)) {
    const removed = removedKinds[row.kind];
    if (removed !== undefined) {
      stale(row.kind, removed);
      continue;
    }
    if (row.kind === 'schedule:interval') {
      report(
        'unsupported-interval',
        'Workers cannot drive @Interval handlers; use a scheduled trigger or a separate Node adapter.',
      );
      continue;
    }
    if (
      ![
        'schedule:cron',
        'cf:queue',
        'cf:queue:module',
        'queue',
        'queue:registration',
        'rpc:client',
        'websocket',
      ].includes(row.kind)
    )
      continue;
    const parsed = metadataSchema.safeParse(row.meta);
    if (!parsed.success) {
      report('invalid-metadata', `Invalid ${row.kind} metadata.`);
      continue;
    }
    const meta = parsed.data;
    if (row.kind === 'rpc:client') {
      // HTTP RPC clients need no Worker binding; declared bindings are mandatory.
      if (meta.binding === undefined) continue;
      const binding = meta.binding;
      if (
        typeof binding !== 'string' ||
        !binding ||
        !target.bindings.some((b) => b.name === binding && b.kind === 'services')
      ) {
        report(
          'missing-service-binding',
          'A declared services binding is missing from the selected environment.',
        );
      }
      continue;
    }
    if (row.kind === 'cf:queue:module') {
      if (!Object.hasOwn(meta, 'consumers') && Object.hasOwn(meta, 'logicalQueue')) {
        stale(
          'cf:queue:module',
          'QueueModule registrations replace consumer mappings (queue:registration)',
        );
        continue;
      }
      const moduleRow = moduleConsumerSchema.safeParse(meta);
      if (!moduleRow.success) {
        report('invalid-metadata', `Invalid ${row.kind} metadata.`);
        continue;
      }
      moduleConsumer = true;
      for (const queue of moduleRow.data.consumers) modulePins.add(queue);
      continue;
    }
    if (row.kind === 'queue:registration') {
      const registration = registrationSchema.safeParse(meta);
      if (!registration.success) {
        report('invalid-metadata', `Invalid ${row.kind} metadata.`);
        continue;
      }
      const { name, binding, consumers } = registration.data;
      const existing = registrations.get(name);
      registrations.set(name, {
        binding: existing?.binding ?? binding,
        consumers: [...new Set([...(existing?.consumers ?? []), ...consumers])],
      });
      continue;
    }
    if (row.kind === 'queue') {
      const processor = queueName.safeParse(meta.queueName);
      if (!processor.success) {
        report('invalid-metadata', `Invalid ${row.kind}.queueName metadata.`);
        continue;
      }
      processedQueues.add(processor.data);
      continue;
    }
    if (row.kind === 'schedule:cron') {
      try {
        const cron = parseCronMetadata(meta);
        if (
          (cron.dialect !== undefined && cron.dialect !== 'cloudflare') ||
          (cron.timeZone !== undefined && cron.timeZone !== 'UTC')
        ) {
          report(
            'incompatible-cron-options',
            'A cron handler explicitly requests options incompatible with Cloudflare UTC delivery.',
          );
        }
        const ambiguity = cronDialectAmbiguity(cron);
        if (ambiguity !== undefined) {
          report(
            'ambiguous-cron-dialect',
            `Cron handler ${JSON.stringify(cron.expression)} declares no dialect, and ` +
              `${ambiguity}, so it fires on different days under Node and under Workers. ` +
              `Declare { dialect: 'cloudflare' } and write the expression for Cloudflare; a ` +
              `Node-only job declares { dialect: 'unix' } and is not deployed as a Worker.`,
          );
        }
      } catch {
        report('invalid-metadata', `Invalid ${row.kind} metadata.`);
        continue;
      }
    }
    if (row.kind === 'websocket') {
      // WsDispatcher contributes { options, ... }; raw class metadata is options itself.
      const options = Object.hasOwn(meta, 'options')
        ? metadataSchema.safeParse(meta.options)
        : parsed;
      const binding = options.success ? options.data.binding : undefined;
      if (
        typeof binding !== 'string' ||
        !target.bindings.some((b) => b.kind === 'durable_objects' && b.name === binding)
      ) {
        report(
          'missing-durable-binding',
          'A WebSocket gateway requires a Durable Object binding in the selected environment.',
        );
      }
      continue;
    }
    const key = row.kind === 'cf:queue' ? 'queueName' : 'expression';
    const value = meta[key];
    if (typeof value !== 'string' || value.trim().length === 0) {
      report('invalid-metadata', `Invalid ${row.kind}.${key} metadata.`);
      continue;
    }
    if (row.kind === 'cf:queue') rawQueues.add(value);
    else {
      handlerCrons.add(value);
      validateCron(value);
    }
  }
  for (const cron of handlerCrons)
    if (!crons.has(cron))
      report(
        'missing-cron-trigger',
        `No exact Wrangler trigger for handler cron ${JSON.stringify(cron)}.`,
      );
  for (const cron of crons)
    if (!handlerCrons.has(cron))
      report(
        'unhandled-cron-trigger',
        `No metadata handler for Wrangler cron ${JSON.stringify(cron)}.`,
      );

  // Registered queues send through Wrangler producer bindings, which name their physical queue.
  const producers = new Map(target.queueProducers.map((row) => [row.binding, row.queue]));
  for (const [name, { binding }] of registrations)
    if (binding !== undefined && !producers.has(binding))
      report(
        'missing-queue-producer',
        `Queue ${JSON.stringify(name)} sends through binding ${JSON.stringify(binding)}, which ` +
          'is not a queues.producers binding of the selected environment.',
      );
  for (const queue of rawQueues)
    if (!target.queueConsumers.includes(queue))
      report(
        'missing-queue-consumer',
        `No selected queue consumer for handler queue ${JSON.stringify(queue)}.`,
      );
  // A native QueueModule consumer receives each processed queue from the
  // physical queues its registration pins, or else from its producer's queue.
  const moduleQueues = new Set<string>();
  const unmapped: string[] = [];
  if (moduleConsumer) {
    for (const name of processedQueues) {
      const registration = registrations.get(name);
      if (!registration) {
        report(
          'unregistered-queue-processor',
          `@Processor(${JSON.stringify(name)}) has no QueueModule.registerQueue({ name: ` +
            `${JSON.stringify(name)} }) in the application, so native deliveries of its jobs ` +
            'are rejected.',
        );
        continue;
      }
      const produced =
        registration.binding === undefined ? undefined : producers.get(registration.binding);
      const physical =
        registration.consumers.length > 0
          ? registration.consumers
          : produced === undefined
            ? []
            : [produced];
      if (physical.length === 0) {
        unmapped.push(name);
        continue;
      }
      for (const queue of physical) {
        moduleQueues.add(queue);
        if (!target.queueConsumers.includes(queue))
          report(
            'missing-queue-consumer',
            `No selected queue consumer for queue ${JSON.stringify(queue)}, which delivers ` +
              `${JSON.stringify(name)} jobs.`,
          );
      }
    }

    // A raw @QueueConsumer owns its physical queue's batches, so the module
    // consumer never receives them (bootstrap rejects a pinned one too).
    const claimed = new Map<string, Set<string>>();
    const claim = (queue: string, name?: string): void => {
      if (!rawQueues.has(queue)) return;
      const names = claimed.get(queue) ?? new Set<string>();
      if (name !== undefined) names.add(name);
      claimed.set(queue, names);
    };
    for (const queue of modulePins) claim(queue);
    for (const [name, registration] of registrations)
      for (const queue of registration.consumers) claim(queue, name);
    for (const name of processedQueues) {
      const registration = registrations.get(name);
      const produced =
        registration?.binding === undefined ? undefined : producers.get(registration.binding);
      if (registration?.consumers.length === 0 && produced !== undefined) claim(produced, name);
    }
    for (const [queue, names] of claimed) {
      const jobs = [...names].map((name) => JSON.stringify(name)).join(', ');
      report(
        'queue-consumer-claimed-by-raw',
        `Queue ${JSON.stringify(queue)} is claimed by @QueueConsumer(${JSON.stringify(queue)}), ` +
          'so the QueueModule consumer never receives its batches' +
          (jobs ? ` and ${jobs} jobs sent to it never reach their @Processor` : '') +
          '. Remove the @QueueConsumer, or route the registered queues through a physical ' +
          'queue that no @QueueConsumer claims.',
      );
    }

    // A physical queue pinned by registrations accepts only their jobs, so an
    // unpinned queue whose producer sends there is rejected and dead-lettered.
    const pinnedTo = new Map<string, string[]>();
    for (const queue of modulePins) pinnedTo.set(queue, []);
    for (const [name, registration] of registrations)
      for (const queue of registration.consumers)
        pinnedTo.set(queue, [...(pinnedTo.get(queue) ?? []), name]);
    for (const [name, { binding, consumers }] of registrations) {
      if (consumers.length > 0 || binding === undefined) continue;
      const produced = producers.get(binding);
      const owners = produced === undefined ? undefined : pinnedTo.get(produced);
      if (produced === undefined || owners === undefined) continue;
      report(
        'queue-sent-to-pinned-queue',
        `Queue ${JSON.stringify(name)} sends through binding ${JSON.stringify(binding)} to ` +
          `${JSON.stringify(produced)}, which QueueModule pins to ` +
          `${owners.map((owner) => JSON.stringify(owner)).join(', ') || 'other queues'}: the ` +
          `consumer rejects ${JSON.stringify(name)} jobs there, so Cloudflare retries and then ` +
          `dead-letters them. Pin it too with QueueModule.registerQueue({ name: ` +
          `${JSON.stringify(name)}, consumer: ${JSON.stringify(produced)} }), or send it through ` +
          'another queue.',
      );
    }
  }
  const moduleConsumers = target.queueConsumers.filter((queue) => !rawQueues.has(queue));
  for (const name of unmapped) {
    if (moduleConsumers.length === 0)
      report(
        'queue-processor-without-consumer',
        `@Processor(${JSON.stringify(name)}) has no queue consumer in the selected environment. ` +
          'Add a queues.consumers entry and pin it with QueueModule.registerQueue({ name: ' +
          `${JSON.stringify(name)}, consumer }).`,
      );
    else
      warnings.push({
        code: 'unverified-queue-consumer',
        message:
          `Queue ${JSON.stringify(name)} names no physical queue, so its consumer is not ` +
          'verified. Pin it with QueueModule.registerQueue({ name, consumer }) or register a ' +
          'binding whose Wrangler producer names its queue.',
      });
  }
  for (const queue of moduleConsumers)
    if (!moduleConsumer || (!moduleQueues.has(queue) && unmapped.length === 0))
      report(
        'unhandled-queue-consumer',
        `No metadata handler for selected queue ${JSON.stringify(queue)}.`,
      );
  warnings.push({
    code: 'static-only',
    message:
      'Snapshot freshness, custom platform handlers, deployed resources, secrets and bundle/runtime behavior are not verified. Run Wrangler and native tests separately.',
  });
  if (target.customBuild)
    warnings.push({
      code: 'custom-build',
      message: 'Wrangler has a custom build command. It was not executed by this check.',
    });
  return { status: errors.length ? 'failed' : 'passed', target, errors, warnings };
}
