// Generated by vela client generate. Do not edit.
import type { HttpApp } from '@velajs/client/http';

export type Schemas = {
  "CreateTodoDto": ({ "done"?: (boolean); "title": (string); [key: string]: unknown; });
  "UpdateTodoDto": ({ "done"?: (boolean); "title"?: (string); [key: string]: unknown; });
};

export type AppType = HttpApp<{
  "/healthz": {
    $get: { input: {}; output: ({ "ok": (boolean); [key: string]: unknown; }); outputFormat: 'json'; status: 200 };
  };
  "/me": {
    $get: { input: {}; output: ({ "email": (string); "id": (string); "name": (string); [key: string]: unknown; }); outputFormat: 'json'; status: 200 };
  };
  "/openapi.json": {
    $get: { input: {}; output: ({ "openapi": (string); "paths": ({ [key: string]: unknown; }); [key: string]: unknown; }); outputFormat: 'json'; status: 200 };
  };
  "/todos": {
    $get: { input: {}; output: unknown; outputFormat: 'json'; status: 200 };
    $post: { input: { json: (Schemas["CreateTodoDto"]); }; output: unknown; outputFormat: 'json'; status: 201 } | { input: { json: (Schemas["CreateTodoDto"]); }; output: unknown; outputFormat: 'json'; status: 400 };
  };
  "/todos/:id": {
    $get: { input: { param: { "id": string; }; }; output: unknown; outputFormat: 'json'; status: 200 } | { input: { param: { "id": string; }; }; output: unknown; outputFormat: 'json'; status: 404 };
    $patch: { input: { param: { "id": string; }; json: (Schemas["UpdateTodoDto"]); }; output: unknown; outputFormat: 'json'; status: 200 } | { input: { param: { "id": string; }; json: (Schemas["UpdateTodoDto"]); }; output: unknown; outputFormat: 'json'; status: 400 } | { input: { param: { "id": string; }; json: (Schemas["UpdateTodoDto"]); }; output: unknown; outputFormat: 'json'; status: 404 };
    $delete: { input: { param: { "id": string; }; }; output: unknown; outputFormat: 'json'; status: 200 } | { input: { param: { "id": string; }; }; output: unknown; outputFormat: 'json'; status: 404 };
  };
}>;
