/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: 4ab624cdf568bfd985974594a0baa7fe)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	PRIVATE_API: Fetcher;
	BROWSER: BrowserRun;
	AI: Ai;
	IMAGES: ImagesBinding;
	DEMO_OWNER: string;
	AI_GATEWAY_ID: string;
	DEMO_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_OWNER" | "AI_GATEWAY_ID" | "DEMO_TOKEN">> {}
}
