/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9dffb0db832ccef2411509e5e2a28540)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	MAIL_QUEUE: Queue;
	MAIL_FROM: "support@example.com";
	REPLY_RECIPIENT: "reader@example.net";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAIL_FROM" | "REPLY_RECIPIENT">> {}
}
