/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: 550715acc63f9e757783e1c3dc3ea902)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: string;
	BETTER_AUTH_SECRET: string;
	VELA_STUDIO_TOKEN: string;
	LIVE_ROOM: DurableObjectNamespace<import("./src/worker").LiveRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "LiveRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "BETTER_AUTH_SECRET" | "VELA_STUDIO_TOKEN">> {}
}
