/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: af2bb9609264fdd5c18c286acdcf2c4a)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: string;
	BETTER_AUTH_SECRET: string;
	VELA_STUDIO_TOKEN: string;
	LIVE_ROOM: DurableObjectNamespace /* LiveRoom */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "BETTER_AUTH_SECRET" | "VELA_STUDIO_TOKEN">> {}
}
