/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 684a5719b4fa0a4d04a1ab6a468622b2)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	ACCESS_TOKEN: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TOKEN">> {}
}
