/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c905f0d637ee504b737353dce390c705)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
