/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4d413482c5f6b5f2f92b3be927bccbf5)
interface __BaseEnv_Env {
	TODOS: KVNamespace;
	TODO_EVENTS: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
