/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: 59860c3ecea78d3ab67e394a3511c90c)
interface __BaseEnv_Env {
	DEMO_OWNER: string;
	DEMO_TENANT: string;
	DEMO_TOKEN: string;
	URL_SIGNING_SECRET: string;
	THREADS: DurableObjectNamespace<import("./src/worker").Threads>;
	REVIEW: Workflow<Parameters<import("./src/worker").ReviewWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Threads";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_OWNER" | "DEMO_TENANT" | "DEMO_TOKEN" | "URL_SIGNING_SECRET">> {}
}
