/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3ba4b4763bb954afff41e9e77a0a7aeb)
interface __BaseEnv_Env {
	TODOS: KVNamespace;
	CHAT_ROOM: DurableObjectNamespace<import("./src/worker").LiveRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "LiveRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
