import type { CrudEndpointName } from './types';

const OVERRIDE_METADATA = 'vela:crud:overrides';

export interface OverrideEntry {
  endpoint: CrudEndpointName;
  methodName: string | symbol;
}

/**
 * Mark a controller method as the implementation for a base CRUD route.
 *
 * The rest of the routes are still generated by `@Crud()`; only the named one
 * is replaced. The override runs as middleware on the matching route — return
 * any value to short-circuit the generated handler, or call `next()` to fall
 * through to it.
 *
 * @example
 * ```ts
 * @Controller('/users')
 * @Crud({ meta: userMeta, adapters: MemoryAdapters })
 * class UserController {
 *   @Override('list')
 *   async customList(c: Context) {
 *     const tenantId = c.req.header('x-tenant-id');
 *     return c.json({ result: store.filterByTenant(tenantId) });
 *   }
 * }
 * ```
 */
export function Override(endpoint: CrudEndpointName): MethodDecorator {
  return (target: object, propertyKey: string | symbol) => {
    const ctor = target.constructor as object;
    const existing: OverrideEntry[] =
      (Reflect.getMetadata(OVERRIDE_METADATA, ctor) as OverrideEntry[] | undefined) ?? [];
    existing.push({ endpoint, methodName: propertyKey });
    Reflect.defineMetadata(OVERRIDE_METADATA, existing, ctor);
  };
}

export function getOverrides(target: object): OverrideEntry[] {
  return (Reflect.getMetadata(OVERRIDE_METADATA, target) as OverrideEntry[] | undefined) ?? [];
}
