/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9604e2b6d9b0c691cbe6258a4adccb53)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
