name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/checkout@v6
        with:
          repository: velajs/vela
          token: ${{ secrets.VELA_TOKEN }}
          path: vela

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Build and pack vela
        working-directory: vela
        run: pnpm install && pnpm run build && pnpm pack --pack-destination ..

      - name: Install dependencies
        run: |
          rm pnpm-lock.yaml
          jq 'del(.devDependencies["@velajs/vela"])' package.json > tmp && mv tmp package.json
          pnpm add ./velajs-vela-*.tgz --save-dev

      - run: pnpm run typecheck

      - run: pnpm run build

      - run: pnpm test

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
