/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: da2ea1a2e4e7ce3568b3c8bff9d86f7b)
interface __BaseEnv_Env {
	PRIMARY_DB: D1Database;
	ANALYTICS_DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
