/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f0ba05974842e3e805c58b2b5eb40364)
interface __BaseEnv_Env {
	PRIMARY_DB: D1Database;
	ANALYTICS_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
